
//敌人
var rivalSide={
	gui:{
		name:'杰尼龟',
		eneRole:"img/mm1.png",
		role:"img/gui.png",
		LV:4,
		bcg:'img/1.jpg',
		top:'40px',
		left:'838px',
        width:'270',
        height:'270',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'288px',
				left:'185px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'288px',
				left:'185px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'288px',
				left:'185px',
		        width:'350'
			}
	    ]
	},
	jjy:{
		name:'角金鱼',
		eneRole:"img/mm2.png",
		role:"img/jjy.png",
		LV:4,
		bcg:'img/2.jpg',
		top:'18px',
		left:'880px',
        width:'270',
        height:'270',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'288px',
				left:'185px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'288px',
				left:'185px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'288px',
				left:'185px',
		        width:'350'
			}
	    ]
	},
	chong:{
		name:'独角虫',
		eneRole:"img/bzp.png",
		role:"img/chong.png",
		LV:4,
		bcg:'img/3.jpg',
		top:'82px',
		left:'900px',
        width:'200',
        height:'200',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'288px',
				left:'185px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'288px',
				left:'185px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'288px',
				left:'185px',
		        width:'350'
			}
	    ]
	},
	lada:{
		name:'拉达',
		eneRole:"img/man.png",
		role:"img/lada.png",
		LV:4,
		bcg:'img/4.jpg',
		top:'106px',
		left:'890px',
        width:'270',
        height:'220',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'288px',
				left:'185px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'288px',
				left:'185px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'288px',
				left:'185px',
		        width:'350'
			}
	    ]
	},
	fish:{
		name:'鲤鱼王',
		eneRole:"img/ben.png",
		role:"img/fish.png",
		LV:4,
		bcg:'img/5.jpg',
		top:'33px',
		left:'874px',
        width:'270',
        height:'270',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'288px',
				left:'185px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'288px',
				left:'185px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'288px',
				left:'185px',
		        width:'350'
			}
	    ]
	}
};


//己方
var ownSide={
	miao:{
		name:'妙蛙种子',
		role:"img/mmzz_by.png",
		LV:4,
		top:'298px',
		left:'185px',
        width:'340',
        height:'300',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'20px',
				left:'840px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'25px',
				left:'850px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'43px',
				left:'860px',
		        width:'350'
			}
	    ]
	},
	pkq:{
		name:'皮卡丘',
		role:"img/pkq_by.png",
		LV:4,
		top:'298px',
		left:'185px',
        width:'377',
        height:'310',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'20px',
				left:'840px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'25px',
				left:'850px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'43px',
				left:'860px',
		        width:'350'
			}
	    ]
	},
	tyxz:{
		name:'秃鹰小子',
		role:"img/tyxz_by.png",
		LV:4,
		top:'298px',
		left:'185px',
        width:'340',
        height:'306',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'20px',
				left:'840px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'25px',
				left:'850px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'43px',
				left:'860px',
		        width:'350'
			}
	    ]
	},
	kd:{
		name:'蚊香蝌蚪',
		role:"img/kd_by.png",
		LV:4,
		top:'382px',
		left:'185px',
        width:'340',
        height:'220',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'20px',
				left:'840px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'25px',
				left:'850px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'43px',
				left:'860px',
		        width:'350'
			}
	    ]
	},
	cao:{
		name:'走路草',
		role:"img/cao_by.png",
		LV:4,
		top:'288px',
		left:'185px',
        width:'340',
        height:'300',
        skill:[
        	{
				pict:"img/wind.gif",
				top:'20px',
				left:'840px',
		        width:'340'
			},
			{
				pict:"img/pap.gif",
				top:'25px',
				left:'850px',
		        width:'380'
			},
			{
				pict:"img/kan.gif",
				top:'43px',
				left:'860px',
		        width:'350'
			}
	    ]
	}
};

