let data = [
    require("./bg/1.png"),
    require("./bg/2.png"),
    require("./bg/3.png"),
    require("./bg/4.png"),
    require("./bg/5.png"),
    require("./bg/6.png"),
    require("./bg/7.png"),
    require("./bg/8.png"),
    require("./bg/9.png"),
    require("./bg/10.png"),
    require("./bg/11.png"),
    require("./bg/12.png"),
    require("./bg/13.png"),
    require("./bg/14.png"),
    require("./bg/15.png"),
    require("./bg/16.png"),
    require("./bg/17.png"),
    require("./bg/18.png"),
    require("./bg/19.png"),
    require("./bg/20.png"),
]
export default data;
